#!/bin/sh

echo "Formatting..."
composer format

echo "Re-staging any files modified by formatting..."
git add -u

echo "Running tests..."
composer test:browser
if [ $? -ne 0 ]; then
    echo "Tests failed. Commit aborted."
    exit 1
fi
